### ISSUE TITLE
Cannot create a connection if an element is selected beforehand

### ISSUE THREAD

**Issue by planger** [eclipsesource/graphical-lsp#120]
I cannot create edges if the source node was already preselected. Maybe the sprotty selection listener is to "greedy" and therefore overrules the feedback drawer listener.

**Comment by planger** [comment]
Spin-off ticket from #115

**Comment by planger** [comment]
After #121 I can't reproduce this issue anymore either, can anyone else?

**Comment by tortmayr** [comment]
Affirmative. Looks like #121 has fixed this as well

**Comment by tortmayr** [comment]
Seems to fixed indirectly. Closing this
