### ISSUE TITLE
Create first release of GLSP

### ISSUE THREAD

**Issue by planger** [eclipsesource/graphical-lsp#123]
I suggest that right after fixing the following issues, we should do an initial release.

- Palette/Tooling support for client #4
- Improve existing palette #80
- Cannot reopen a diagram #76
- Move action should make use of move hints #28
- Support for reparenting (move into another container); there is no issue yet.

I'll create a milestone to reflect that as well.

**Comment by tortmayr** [comment]
Server components are released and synced with the maven central repository.
For the release of the name components, we should wait until the next sprotty release (19-03).
