### ISSUE TITLE
Create eclispe/sprotty-theia fork in "EclipseSource" domain

### ISSUE THREAD

**Issue by tortmayr** [eclipsesource/graphical-lsp#127]
Currently our fork for the theia sprotty clue code is based on the deprecated theiaIde/theia-sprotty repository. To make use of the latest glue code contributions we need to migrate to a eclipse/sprotty-theia fork.

@planger  Could you please set up a inital fork in the EclipseSource domain?

**Comment by planger** [comment]
Sure, created it here: https://github.com/eclipsesource/sprotty-theia
You should have write access to it.
