### ISSUE TITLE
split-n-sort extension introduced new line on save

### ISSUE THREAD

**Issue by tortmayr** [eclipsesource/graphical-lsp#199]
There is an issue with the `split-n-sort` vs code extension:
Every time the file is saved a new blank line is added after the last import statement.
@planger Do you know if the extension is configurable so that we can disable this behavior?
![saveissue_peek](https://user-images.githubusercontent.com/2311075/53944574-f8e1f580-40bf-11e9-8437-d711bd2a4b4c.gif)

**Comment by planger** [comment]
Oh, right! Good catch!
I don't think it is configurable, but I think we should raise a bug against `split-n-sort`. Quickly browsing through the code, it looks like this line is the culprit:
https://github.com/mflorence99/import-splitnsort/blob/58d4c1d63f64e85988f9eaea9861569d9e0e506f/src/parser.ts#L91

**Comment by planger** [comment]
I've opened https://github.com/mflorence99/import-splitnsort/issues/3

**Comment by tortmayr** [comment]
Having a closer look at this issue it seems like this behaviour is caused by our vs code configuration.
Using both `split-n-sort` and `organize import on save` introduces the new line on each save. If I remove `organize import on save` from the  settings `split-n-sort` works as expected
