### ISSUE TITLE
Document the adaptations and changes made to the GLS protocol

### ISSUE THREAD

**Issue by tortmayr** [eclipsesource/graphical-lsp#21]
The protocol used by our GLSP implementation should be documented somewhere. We should probably fork  https://github.com/ObeoNetwork/GraphicalServerProtocol to the EclipseSource domain and change the specfication.md file accordingly

**Comment by planger** [comment]
I pushed a PR to the spec document: https://github.com/eclipsesource/GraphicalServerProtocol/pull/1
I found a few inconsistencies while working on the spec document. I'll open separate issues for them.

**Comment by planger** [comment]
Fixed via https://github.com/eclipsesource/GraphicalServerProtocol/pull/1
I also changed the link from the readme to directly point to the spec. I opened #92 and #93 regarding the inconsistencies I found while working on updating the protocol spec.
