### ISSUE TITLE
Direct editing support 

### ISSUE THREAD

**Issue by tortmayr** [eclipsesource/graphical-lsp#27]
Is should be possible to edit the labels/names of components by double-clicking on the label.

**Comment by planger** [comment]
See also https://github.com/eclipse/sprotty/pull/13

**Comment by planger** [comment]
Added generic UI to sprotty: https://github.com/eclipse/sprotty/issues/83
Once merged, this needs to be hooked up with GLSP by forwarding the `ApplyLabelEditAction` to the server.
