### ISSUE TITLE
Incorporate new sprotty features into glsp-client

### ISSUE THREAD

**Issue by tortmayr** [eclipsesource/graphical-lsp#367]
The sprotty project as currently a lot of drive because they are trying to publish a new major release before ECE 19 (0.7.0).  I had quick look at the recent PRs and it looks like there a lot new features/improvements that are potentially interesting for GLSP.

@planger Maybe we should aim to align the initial eclipse/glsp contributions with the next sprotty release to ensure a stable baseline?

**Comment by planger** [comment]
Yes, I'm all for aligning the GLSP release with the Sprotty releases.
Thanks!


Tobias Ortmayr <notifications@github.com> schrieb am Mo., 9. Sep. 2019,
15:40:

**Comment by tortmayr** [comment]
Resolved with #387
