### ISSUE TITLE
Enable client-side persisting of the model

### ISSUE THREAD

**Issue by planger** [eclipsesource/graphical-lsp#63]
Currently, only the server can persist the model (see fix for #36 and default handler of the `SaveModelAction`). I do believe that both is a valid use case in general, however, following the usual LSP architecture, it is actually the client's responsibility to persist the model. I think it is fair that the server is still notified about the change, however, the client really performs the save then directly into the workspace.

Therefore, I think the `SaveableGLSPModelSource` should be capable of saving directly to the workspace. Clients should be able to enable or disable client-side save depending on whether the server or the client should be responsable for persistence.

**Comment by tortmayr** [comment]
Seems like the base sprotty diagram server already has support for that
https://github.com/eclipse/sprotty/blob/832ff1e21c7399a16e9f206700d71335d56407cb/src/model-source/diagram-server.ts#L155

We just need to initialize the modelStorage accordingly

**Comment by CamilleLetavernier** [comment]
> I do believe that both is a valid use case in general, however, following the usual LSP architecture, it is actually the client's responsibility to persist the model.

While that makes a lot of sense for text-based editors, it's not so true for diagram editors, where the serialization format is typically an implementation detail (Potentially not even a single file)

**Comment by tortmayr** [comment]
@planger any additional thoughts on this? I agree with @CamilleLetavernier that persisting in GLSP should probably be the server's responsibility. Especially since the client doesn't have knowledge about the concrete language implementation a could only persist the received SModel.

I'm going to close this if there are no objections.
