### ISSUE TITLE
Improve tool selection in the context of multi-diagrams

### ISSUE THREAD

**Issue by tortmayr** [eclipsesource/graphical-lsp#78]
Selecting a tool from the palette doesn't work reliably with multiple clients (probably related to the Operation Service handling).

**Comment by planger** [comment]
Is this still open? I think we've addressed this issue quite a long time ago when introducing the tool manager and removing the operation service, right?

**Comment by tortmayr** [comment]
Yeah I think so too.This should be fixed since each diagram has its own DI-container and toolmanager respectively
